# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[remote.github]
owner = "0rax"
repo = "BerryOS"

[changelog]
body = """
{% for commit in commits %}
  {%- if commit.remote.pr_title -%}
    {%- set commit_message = commit.remote.pr_title -%}
  {%- else -%}
    {%- set commit_message = commit.message -%}
  {%- endif -%}
  - {{ commit_message | split(pat="\n") | first | trim }} \
    {% if commit.remote.pr_number -%}
      (#{{ commit.remote.pr_number }} by @{{ commit.remote.username }})
    {%- endif %}
  {%- raw %}\n{% endraw -%}
{%- endfor -%}
"""
trim = true
render_always = true

[git]
conventional_commits = false
filter_unconventional = false
require_conventional = false
split_commits = false
protect_breaking_commits = false
commit_parsers = [
  { field = "author.name", pattern = "dependabot\\[bot\\]", skip = true },
  { field = "remote.pr_labels", pattern = "dependencies", skip = true },
  { field = "remote.pr_labels", pattern = "skip-changelog", skip = true }
]
filter_commits = false
sort_commits = "oldest"
recurse_submodules = false
ignore_tags = "bookworm-nightly"
