version-template: "$COMPLETE"
name-template: "BerryOS Bookworm $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
change-template: "- $TITLE (#$NUMBER by @$AUTHOR)"
template: |
  ## Changelog

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
exclude-labels:
  - 'skip-changelog'
  - 'dependencies'
