version: '3.8'

services:
  builder:
    image: berryos-bootstraper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/bootstrap
    working_dir: /opt/bootstrap
    privileged: true
