version: '3.7'

services:
  builder:
    image: berryos-bootstraper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/bootstrap
    working_dir: /opt/bootstrap
    cap_add:
      - 'ALL'
