source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
group :jekyll_plugins do
end
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end
gem "wdm", "~> 0.1.0", :install_if => Gem.win_platform?
gem "webrick", "~> 1.7"
gem "kramdown-parser-gfm"
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "rubyzip", "~> 2.3.0"
gem "rouge"
