name: Generate Changelog

on:
  workflow_call:
    inputs:
      debian_release:
        type: string
        description: "Base Debian release"
        default: bookworm
      os_version:
        type: string
        description: "OS Version"
        default: "nightly"
    outputs:
      name:
        description: "Release name"
        value: ${{ jobs.generate.outputs.name }}
      tag_name:
        description: "Release tag"
        value: ${{ jobs.generate.outputs.tag_name }}
      content:
        description: "Changelog content"
        value: ${{ jobs.generate.outputs.content }}

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.env.outputs.name }}
      tag_name: ${{ steps.env.outputs.tag_name }}
      content: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate environment
        id: env
        shell: bash
        env:
          OS_VERSION: ${{ inputs.os_version }}
          DEBIAN_RELEASE: ${{ inputs.debian_release }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "name=BerryOS ${DEBIAN_RELEASE^} ${OS_VERSION^}" | tee -a "${GITHUB_OUTPUT}"
          echo "tag_prev=$(gh release view --json tagName -q .tagName)" | tee -a "${GITHUB_OUTPUT}"
          echo "tag_name=${DEBIAN_RELEASE}/${OS_VERSION}" | tee -a "${GITHUB_OUTPUT}"
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --tag "${{ steps.env.outputs.tag_name }}" -- "${{ steps.env.outputs.tag_prev }}..HEAD"
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
