name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch release workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "release.yaml",
              ref: "main",
              inputs: {
                os_version: "nightly",
                debian_release: "bookworm"
                publish: true
                prelease: true
              }
            });
