name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: "bookworm-nightly"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
    uses: ./.github/workflows/builder.yaml
    with:
      os_version: nightly
      debian_release: bookworm
      build_arch: ${{ matrix.build_arch }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          pattern: |
            berryos-*-image
          merge-multiple: true
      - name: Update nightly release
        uses: ncipollo/release-action@v1
        with:
          tag: bookworm-nightly
          name: BerryOS Bookworm Nightly
          prerelease: true
          body: |
            ## Nightly Builds

            This is an automated nightly release. It includes daily built version of the BerryOS images.

            ### Why use a nightly build?

            Nightly builds allow you to make sure you are using an image that includes the latest version of all install packages. Making the initial setup of BerryOS faster.

            It shouldn't be much different than using a stable release, but it might be a bit more unstable, especially during major updates (when BerryOS needs to be synced with the latest changes from Raspberry Pi OS).

            ### Disclaimer

            These builds are provided without any warranty. No manual testing or benchmarks have been performed.

            If you prefer a stable release, please download the [latest stable release](https://github.com/0rax/BerryOS/releases/latest).

            ## Compatibility

            - `BerryOS/armhf`
              - Image: [`berryos-armhf-bookworm-nightly.img.xz`](https://github.com/0rax/BerryOS/releases/download/bookworm-nightly/berryos-armhf-bookworm-nightly.img.xz)
              - Compatibility: all Raspberry Pi models

            - `BerryOS/arm64`
              - Image [`berryos-arm64-bookworm-nightly.img.xz`](https://github.com/0rax/BerryOS/releases/download/bookworm-nightly/berryos-arm64-bookworm-nightly.img.xz)
              - Compatibility:
                - Raspberry Pi 3B, 3B+, 4 B & 400
                - Compute Module 3, 3+ & 4
                - Raspberry Pi Zero 2 W
                - Raspberry Pi 5

            ## Issues

            If you find any issues when using a nightly build, please report them to the [issue tracker](https://github.com/0rax/BerryOS/issues). Make sure to include the content of `/etc/rpi-issue` in your report so we can pin-point the specific build you are using.
          artifacts: "out/*"
          allowUpdates: true
          removeArtifacts: true
