name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

concurrency:
  group: "bookworm-nightly"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
        include:
          - build_arch: armhf
            job_id: build_armhf
          - build_arch: arm64
            job_id: build_arm64
    name: ${{ matrix.job_id }}
    uses: ./.github/workflows/builder.yaml
    with:
      debian_release: bookworm
      os_version: nightly
      build_arch: ${{ matrix.build_arch }}
  changelog:
    uses: ./.github/workflows/changelog.yaml
    with:
      debian_release: "bookworm"
      os_version: "nightly"
  release:
    needs: [changelog, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          pattern: |
            berryos-*-image
          merge-multiple: true
      - name: Update nightly release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.changelog.outputs.tag_name }}
          name: ${{ needs.changelog.outputs.name }}
          draft: false
          prerelease: true
          target_commitish: ${{ github.sha }}
          body: |
            ## Nightly Builds

            This is an automated nightly release. It includes daily built version of the BerryOS images.

            ### Why use a nightly build?

            Nightly builds allow you to make sure you are using an image that includes the latest version of all install packages. Making the initial setup of BerryOS faster.

            It shouldn't be much different than using a stable release, but it might be a bit more unstable, especially during major updates (when BerryOS needs to be synced with the latest changes from Raspberry Pi OS).

            ### Disclaimer

            These builds are provided without any warranty. No manual testing or benchmarks have been performed.

            If you prefer a stable release, please download the [latest stable release](https://github.com/${{ github.repository }}/releases/latest).

            ## Changes since last stable release

            ${{ needs.changelog.outputs.content }}

            ## Compatibility

            - `BerryOS/armhf`
              - Image: [`${{ needs.build_armhf.outputs.image }}`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/${{ needs.build_armhf.outputs.image }})
              - Compatibility: all Raspberry Pi models

            - `BerryOS/arm64`
              - Image [`${{ needs.build_arm64.outputs.image }}`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/${{ needs.build_arm64.outputs.image }})
              - Compatibility:
                - Raspberry Pi 3B, 3B+, 4 B & 400
                - Compute Module 3, 3+ & 4
                - Raspberry Pi Zero 2 W
                - Raspberry Pi 5

            ## Issues

            If you find any issues when using a nightly build, please report them to the [issue tracker](https://github.com/${{ github.repository }}/issues). Make sure to include the the content of `/etc/rpi-issue` (also available in `/boot/firmware/issue.txt`) in your report so we can pin-point the specific build you are using.
          files: out/*
          fail_on_unmatched_files: true
      - name: Update nightly tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.updateRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/${{ needs.changelog.outputs.tag_name }}',
              sha: context.sha
            });
