name: Nightly Build

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      debian_release: bookworm
      os_version: nightly
      publish: true
      prerelease: true
