name: Release

on:
  workflow_dispatch:
    inputs:
      os_version:
        type: string
        description: "OS Version"
        default: "nightly"
      debian_release:
        type: choice
        required: true
        description: "Base Debian release"
        default: bookworm
        options:
          - bullseye
          - bookworm

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
    uses: ./.github/workflows/builder.yaml
    with:
      os_version: ${{ inputs.os_version }}
      debian_release: ${{ inputs.debian_release }}
      build_arch: ${{ matrix.build_arch }}
