name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      os_version:
        type: string
        description: "OS Version"
        default: "nightly"
      debian_release:
        type: choice
        required: true
        description: "Base Debian release"
        default: bookworm
        options:
          - bullseye
          - bookworm

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
    uses: ./.github/workflows/builder.yaml
    with:
      os_version: ${{ inputs.os_version }}
      debian_release: ${{ inputs.debian_release }}
      build_arch: ${{ matrix.build_arch }}
  draft-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          pattern: |
            berryos-*-image
          merge-multiple: true
      - name: Generate environment
        env:
          OS_VERSION: ${{ inputs.os_version }}
          DEBIAN_RELEASE: ${{ inputs.debian_release }}
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "RELEASE_PREV=$(gh release view --json tagName -q .tagName)" | tee -a "${GITHUB_ENV}"
          echo "RELEASE_NAME=BerryOS ${DEBIAN_RELEASE^} ${OS_VERSION^}" | tee -a  "${GITHUB_ENV}"
          echo "RELEASE_TAG=${DEBIAN_RELEASE}/${OS_VERSION}" | tee -a "${GITHUB_ENV}"
          echo "ARTIFACT_SUFFIX=${DEBIAN_RELEASE,,}-${OS_VERSION//.}" | tee -a "${GITHUB_ENV}"
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: .github/cliff.toml
          args: --tag "${RELEASE_TAG}" -- "${RELEASE_PREV}..HEAD"
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_NAME }}
          draft: true
          target_commitish: ${{ github.sha }}
          body: |
            ## Changelog

            ${{ steps.git-cliff.outputs.content }}

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ env.RELEASE_PREV }}...${{ env.RELEASE_TAG }}

            ## Compatibility

            - `BerryOS/armhf`
              - Image: [`berryos-armhf-${{ env.ARTIFACT_SUFFIX }}.img.xz`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/berryos-armhf-${{ env.ARTIFACT_SUFFIX }}.img.xz)
              - Compatibility: all Raspberry Pi models

            - `BerryOS/arm64`
              - Image [`berryos-arm64-${{ env.ARTIFACT_SUFFIX }}.img.xz`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/berryos-arm64-${{ env.ARTIFACT_SUFFIX }}.img.xz)
              - Compatibility:
                - Raspberry Pi 3B, 3B+, 4 B & 400
                - Compute Module 3, 3+ & 4
                - Raspberry Pi Zero 2 W
                - Raspberry Pi 5

            ## Issues

            If you find any issues when using this release, please report them to the [issue tracker](https://github.com/${{ github.repository }}/issues). Make sure to include the complete name of the release you are using or the content of `/etc/rpi-issue` in your report.
          files: out/*
          fail_on_unmatched_files: true
