name: Release

on:
  workflow_dispatch:
    inputs:
      os_version:
        type: string
        default: "nightly"
      debian_version:
        type: choice
        required: true
        default: 12
        options:
          - 11
          - 12
      debian_release:
        type: choice
        required: true
        default: bookworm
        options:
          - bullseye
          - bookworm

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
    uses: ./.github/workflows/builder.yaml
    with:
      os_version: nightly
      debian_version: 12
      debian_release: bookworm
      build_arch: ${{ matrix.build_arch }}
