name: Release

on:
  workflow_dispatch:
    inputs:
      os_version:
        type: string
        description: "OS Version"
        default: "nightly"
      debian_release:
        type: choice
        required: true
        description: "Base Debian release"
        default: bookworm
        options:
          - bullseye
          - bookworm

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
    uses: ./.github/workflows/builder.yaml
    with:
      os_version: ${{ inputs.os_version }}
      debian_release: ${{ inputs.debian_release }}
      build_arch: ${{ matrix.build_arch }}
  draft-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          pattern: |
            berryos-*-image
          merge-multiple: true
      - name: Generate release-note
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ input.debian_release }}-${{ input.os_version }}
          name: BerryOS ${{ input.debian_release }} ${{ input.os_version }}
          draft: true
          generateReleaseNotes: true
          artifacts: "out/*"
          allowUpdates: false
          skipIfReleaseExists: true
          updateOnlyUnreleased: true
          removeArtifacts: true
