name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      debian_release:
        type: choice
        required: true
        description: "Base Debian release"
        default: bookworm
        options:
          - bullseye
          - bookworm
      os_version:
        type: string
        description: "OS Version"
        default: "nightly"

concurrency:
  group: "${{ inputs.debian_release }}-${{ inputs.os_version }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        build_arch: ["armhf", "arm64"]
        include:
          - build_arch: armhf
            job_id: build_armhf
          - build_arch: arm64
            job_id: build_arm64
    name: ${{ matrix.job_id }}
    uses: ./.github/workflows/builder.yaml
    with:
      debian_release: ${{ inputs.debian_release }}
      os_version: ${{ inputs.os_version }}
      build_arch: ${{ matrix.build_arch }}
  changelog:
    uses: ./.github/workflows/changelog.yaml
    with:
      debian_release: ${{ inputs.debian_release }}
      os_version: ${{ inputs.os_version }}
  release:
    needs: [changelog, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out/
          pattern: |
            berryos-*-image
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.changelog.outputs.tag_name }}
          name: ${{ needs.changelog.outputs.name }}
          draft: true
          target_commitish: ${{ github.sha }}
          body: |
            ## Changelog

            ${{ needs.changelog.outputs.content }}

            ## Compatibility

            - `BerryOS/armhf`
              - Image: [`${{ needs.build_armhf.outputs.image }}`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/${{ needs.build_armhf.outputs.image }})
              - Compatibility: all Raspberry Pi models

            - `BerryOS/arm64`
              - Image [`${{ needs.build_arm64.outputs.image }}`](https://github.com/${{ github.repository }}/releases/download/${{ env.RELEASE_TAG }}/${{ needs.build_arm64.outputs.image }})
              - Compatibility:
                - Raspberry Pi 3B, 3B+, 4 B & 400
                - Compute Module 3, 3+ & 4
                - Raspberry Pi Zero 2 W
                - Raspberry Pi 5

            ## Issues

            If you find any release when using this build, please report them to the [issue tracker](https://github.com/${{ github.repository }}/issues). Make sure to include the the content of `/etc/rpi-issue` (also available in `/boot/firmware/issue.txt`) in your report so we can pin-point the specific build you are using.
          files: out/*
          fail_on_unmatched_files: true
